DECLARE	@return_value int,
		@o_guid sessionid,
		@o_login_client_id uddt_client_id,
		@o_login_locale_id uddt_locale_id,
		@o_country_code uddt_country_code,
		@o_default_password_ind uddt_varchar_1,
		@o_date_display_format uddt_varchar_10,
		@o_timezone_id uddt_tinyint,
		@o_location_code uddt_varchar_10,
		@o_currency_code uddt_varchar_3,
		@o_software_product_id uddt_varchar_10,
		@o_software_product_version uddt_varchar_5,
		@o_software_product_subversion uddt_varchar_3,
		@o_last_login_date uddt_date,
		@o_last_login_hour uddt_hour,
		@o_last_login_minute uddt_minute,
		@o_user_group_id uddt_nvarchar_10,
		@o_photo_reference uddt_nvarchar_255,
		@o_title uddt_nvarchar_10,
		@o_first_name uddt_nvarchar_50,
		@o_middle_name uddt_nvarchar_50,
		@o_last_name uddt_nvarchar_50,
		@o_company_noof_levels uddt_tinyint,
		@o_employee_id uddt_employee_id,
		@o_package_id uddt_varchar_15,
		@o_user_group_type uddt_varchar_2,
		@o_dealer_code uddt_nvarchar_20,
		@o_dealer_org_level_no uddt_tinyint,
		@o_dealer_org_level_code uddt_nvarchar_15,
		@o_employee_org_level_no uddt_tinyint,
		@o_employee_org_level_code uddt_nvarchar_15,
		@errorNo errorno

EXEC	@return_value = [dbo].[sp_authenticate_user]
		@i_sessionId = '7E5851F3-B36A-408E-A0DA-49167A058B65',
		@i_userId = 'cappvisitor',
		@i_client_id = 'demo',
		@i_locale_id = 'en-us',
		@i_country_code = 'in',
		@i_login_client_id = 'demo',
		@i_login_user_id = 'Oemseeng',
		@i_login_country_code = 'in',
		@i_device = '1a2c55d6c885c4db',
		@i_browser = 'com.selfservit.demo/Android/GooglePlayStore',
		@i_ip_address = '',
		@i_channel_id = 'MOBILE',
		@s_login_salt = 'rvJdM6No8naEwuaWbmJTqFl+ncM=',
		@o_guid = @o_guid OUTPUT,
		@o_login_client_id = @o_login_client_id OUTPUT,
		@o_login_locale_id = @o_login_locale_id OUTPUT,
		@o_country_code = @o_country_code OUTPUT,
		@o_default_password_ind = @o_default_password_ind OUTPUT,
		@o_date_display_format = @o_date_display_format OUTPUT,
		@o_timezone_id = @o_timezone_id OUTPUT,
		@o_location_code = @o_location_code OUTPUT,
		@o_currency_code = @o_currency_code OUTPUT,
		@o_software_product_id = @o_software_product_id OUTPUT,
		@o_software_product_version = @o_software_product_version OUTPUT,
		@o_software_product_subversion = @o_software_product_subversion OUTPUT,
		@o_last_login_date = @o_last_login_date OUTPUT,
		@o_last_login_hour = @o_last_login_hour OUTPUT,
		@o_last_login_minute = @o_last_login_minute OUTPUT,
		@o_user_group_id = @o_user_group_id OUTPUT,
		@o_photo_reference = @o_photo_reference OUTPUT,
		@o_title = @o_title OUTPUT,
		@o_first_name = @o_first_name OUTPUT,
		@o_middle_name = @o_middle_name OUTPUT,
		@o_last_name = @o_last_name OUTPUT,
		@o_company_noof_levels = @o_company_noof_levels OUTPUT,
		@o_employee_id = @o_employee_id OUTPUT,
		@o_package_id = @o_package_id OUTPUT,
		@o_user_group_type = @o_user_group_type OUTPUT,
		@o_dealer_code = @o_dealer_code OUTPUT,
		@o_dealer_org_level_no = @o_dealer_org_level_no OUTPUT,
		@o_dealer_org_level_code = @o_dealer_org_level_code OUTPUT,
		@o_employee_org_level_no = @o_employee_org_level_no OUTPUT,
		@o_employee_org_level_code = @o_employee_org_level_code OUTPUT,
		@errorNo = @errorNo OUTPUT

SELECT	@o_guid as N'@o_guid',
		@o_login_client_id as N'@o_login_client_id',
		@o_login_locale_id as N'@o_login_locale_id',
		@o_country_code as N'@o_country_code',
		@o_default_password_ind as N'@o_default_password_ind',
		@o_date_display_format as N'@o_date_display_format',
		@o_timezone_id as N'@o_timezone_id',
		@o_location_code as N'@o_location_code',
		@o_currency_code as N'@o_currency_code',
		@o_software_product_id as N'@o_software_product_id',
		@o_software_product_version as N'@o_software_product_version',
		@o_software_product_subversion as N'@o_software_product_subversion',
		@o_last_login_date as N'@o_last_login_date',
		@o_last_login_hour as N'@o_last_login_hour',
		@o_last_login_minute as N'@o_last_login_minute',
		@o_user_group_id as N'@o_user_group_id',
		@o_photo_reference as N'@o_photo_reference',
		@o_title as N'@o_title',
		@o_first_name as N'@o_first_name',
		@o_middle_name as N'@o_middle_name',
		@o_last_name as N'@o_last_name',
		@o_company_noof_levels as N'@o_company_noof_levels',
		@o_employee_id as N'@o_employee_id',
		@o_package_id as N'@o_package_id',
		@o_user_group_type as N'@o_user_group_type',
		@o_dealer_code as N'@o_dealer_code',
		@o_dealer_org_level_no as N'@o_dealer_org_level_no',
		@o_dealer_org_level_code as N'@o_dealer_org_level_code',
		@o_employee_org_level_no as N'@o_employee_org_level_no',
		@o_employee_org_level_code as N'@o_employee_org_level_code',
		@errorNo as N'@errorNo'

SELECT	'Return Value' = @return_value

GO
