delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type = 'CUSTCONTCATG'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'CUSTCONTCATG', 'OWNER', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'CUSTCONTCATG', 'SITEINCHG', 'system'


delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type = 'CUSTCONTTYPE'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'CUSTCONTTYPE', 'OWNER', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'CUSTCONTTYPE', 'SITEINCHG', 'system'

delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type in ('CQMEQUIPCATG')

Insert into code_table (company_id, country_code, code_type, code, last_update_id)
select 'acgw','in','CQMEQUIPCATG','CAP','system'
Insert into code_table (company_id, country_code, code_type, code, last_update_id)
select 'acgw','in','CQMEQUIPCATG','MA','system'
Insert into code_table (company_id, country_code, code_type, code, last_update_id)
select 'acgw','in','CQMEQUIPCATG','PM','system'


delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type = 'ANCILLARYSTATUS'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'ANCILLARYSTATUS', 'O', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'ANCILLARYSTATUS', 'A', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'ANCILLARYSTATUS', 'I', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'ANCILLARYSTATUS', 'CO', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'ANCILLARYSTATUS', 'CL', 'system'


delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type = 'WFLOWEVERBANCILLARY'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'WFLOWEVERBANCILLARY', 'CLOSE', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'WFLOWEVERBANCILLARY', 'COMPLETE', 'system'

insert into code_table(company_id, country_code, code_type, code, last_update_id)
select 'acgw', 'in', 'WFLOWEVERBANCILLARY', 'GENERATEPE', 'system'




delete from code_table where company_id = 'acgw' and country_code = 'in' and code_type = 'COUNTRYDIALCODE'

INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+93', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+355', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+213', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1684', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+376', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+244', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1264', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+672', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1268', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+54', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+374', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+297', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+61', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+43', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+994', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1242', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+973', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+880', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1246', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+375', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+32', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+501', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+229', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1441', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+975', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+591', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+387', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+267', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+55', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+246', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+673', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+359', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+226', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+257', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+855', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+237', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+238', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+345', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+236', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+235', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+56', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+86', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+57', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+269', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+242', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+243', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+682', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+506', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+225', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+385', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+53', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+357', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+420', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+45', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+253', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1767', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1849', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+593', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+20', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+503', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+240', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+291', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+372', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+251', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+298', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+679', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+358', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+33', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+594', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+689', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+241', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+220', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+995', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+49', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+233', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+350', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+30', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+299', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1473', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1671', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+502', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+224', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+245', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+509', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+379', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+504', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+852', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+36', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+354', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+91', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+62', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+98', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+964', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+353', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+972', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+39', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1876', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+81', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+962', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+77', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+254', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+686', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+850', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+82', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+965', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+996', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+856', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+371', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+961', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+266', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+231', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+218', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+423', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+370', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+352', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+853', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+389', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+261', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+265', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+60', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+960', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+223', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+356', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+692', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+596', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+222', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+230', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+262', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+52', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+691', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+373', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+377', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+976', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+382', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1664', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+212', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+258', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+95', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+264', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+674', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+977', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+31', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+599', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+687', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+64', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+505', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+227', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+234', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+683', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1670', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+47', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+968', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+92', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+680', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+970', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+507', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+675', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+595', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+51', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+63', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+872', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+48', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+351', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1939', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+974', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+40', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+7', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+250', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+290', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1869', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1758', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+590', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+508', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1784', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+685', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+378', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+239', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+966', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+221', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+381', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+248', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+232', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+65', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+421', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+386', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+677', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+252', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+27', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+211', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+500', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+34', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+94', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+249', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+597', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+268', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+46', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+41', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+963', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+886', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+992', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+255', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+66', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+670', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+228', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+690', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+676', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1868', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+216', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+90', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+993', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1649', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+688', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+256', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+380', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+971', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+44', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+598', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+998', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+678', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+58', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+84', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1284', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+1340', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+681', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+967', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+260', 'system'
INSERT into code_table (company_id, country_code, code_type, code, last_update_id) SELECT 'acgw', 'in', 'COUNTRYDIALCODE', '+263', 'system'
