
grant execute on sp_retrieve_manage_custom_info_list_customer_survey to gwell_in_appuser
grant execute on sp_generate_customer_survey to gwell_in_appuser
grant execute on sp_retrieve_manage_custom_info_detail_customer_survey to gwell_in_appuser
grant execute on sp_retrieve_listof_values_gwell to gwell_in_appuser
grant execute on sp_save_manage_custom_info_customer_survey to gwell_in_appuser
grant execute on sp_update_ancillary_request_wfeventverb_status_change_cs_gwell to gwell_in_appuser
grant execute on sp_save_file_to_attachment_master to gwell_in_appuser

grant execute on sp_retrieve_manage_custom_info_list_customer_survey to gwell_in_processuser
grant execute on sp_generate_customer_survey to gwell_in_processuser
grant execute on sp_retrieve_manage_custom_info_detail_customer_survey to gwell_in_processuser
grant execute on sp_retrieve_listof_values_gwell to gwell_in_processuser
grant execute on sp_save_manage_custom_info_customer_survey to gwell_in_processuser
grant execute on sp_update_ancillary_request_wfeventverb_status_change_cs_gwell to gwell_in_processuser
grant execute on sp_save_file_to_attachment_master to gwell_in_processuser

